input_ = """wwwnwsenwnwnwnwnwnewnewsewnwnwnww
nenwnwnewnweewsenwenwnwwswwnwswsw
seswswseneeeswswnwnwswseswnwswswswswsw
swenenwneswswswswsenwswswnwenenwseswsw
wneneenwseeeewneeseneeeneeenenene
wwwwenwwwwwnwnewwnwswwwwwse
neneneneneneeneswneeneenwneeneneenesw
seneseswseseswswseseswswseswsewsesesesw
enweneeeeeseeeesw
wwwsewswwwwswwenwneew
sesweenwseeneeeswneeseeeseswenwsese
seswswwswswswswseswswnwswswene
swwnwwwwwwswnwwwseswwwwwseww
wwnewwsewwwwswwneseweewwnw
wswswseneswswseswseneswseswseswswseswnesw
nenwnwneneseneeneswnewenweeswneeese
wwenwwwwnwwwnewsewwnwwwswwnw
newnwswneswswswneeeneenenee
swwsewswswswnwswswswnewewseswswswsw
eseneeenwseesweesw
wnenenenwnenenwnenwnwnenwnwsesenwnesene
eswneeeeeeeeneeeneenenewnee
enwenweeweewesesesweswswnweew
eseeseseseeswsewswww
wseeneewnwswswenweee
swwneswswwwwwswwswwwswwseswww
wesesesewsweseenwnesewneneswseswsw
nwswsesenwswnenenwenenwne
neeneseenenweneneneeeweeneeeswe
wwnwnwwwwsenwnwwnwwwnwwnwnwnw
eswnewswwnwnwwnwnwnwenwwsenewenww
wswsenwsewswseeneseseswswswneseswsw
sewswewwwnwwwnwwneewnwnwnwswnw
wsweswswwnwwsweswswswswnwswswswswswswe
swneseswswswswswsesenwsesw
neeeesewseenweeesweseeeeeee
nenenenenwnenenwneneneneeswswnwnenenwnwnw
nwwwewnwwnwwwwnwwnewnwwwwsenw
senwseeeesenwseeeseenwsweseseswnee
seseseeesenwseseeseeseseesesese
nwsesesesenwseseeseseseswewseswswswsw
wwwwnwwwwwnwnenwnwnwewnwwswww
neneneneswneswneneeeenwneneneeenene
seswnwseswsenenwnewseneswsenwsenwseenwswse
neeswwewwwnwneswnwwswswnw
eswwwswwnwwswneswwwsweswwweww
nwswwsewneeeneswneeeeeneeneneesw
eeswewwneseneneeneeeneseeeneneee
seseewseeseneweeeweesewsenewe
swseswwswneswswswsewsweswnwswseswwe
nwnwenwnewnwsenwsewwnwwnwnwwwnewnw
nenwsesesenwwnwsewenwwwwweswwwwe
nesenweseeeseeswsewsewswwseeeese
sewwswseseseneseswnwesenwseesenwenw
weseseseesesesesesenwseseseseesesese
swwnwnwnewnwnwwnwwwew
nwnwnwnwnenwswnwnwnwnwnwwnwnwenwsesesew
swsewwneswwnwswseswwneswswsewnewnew
wwwwnwwswwnwnwewwwwwwnwwnw
seseseseseeseseeseewnweseswnwesesese
nwwnenwnwwnenenwnwnwnwneneenenenwnenwse
nwwsenwnwnewnwwwnwwnwnwnwwnwnwwsenww
sesewsesenweseseseseseseswsesese
seewneswwwwnwwwseswwnwewnwnwnw
neneneneneneswneneneswswe
wwwwwwwwsenwwwwwwwwww
wnwwwnwwnwsewnwwwwwwswe
nwswnwnwewnwsenwneneneneswnwenene
senweweneseeweeeseneeeweeenw
wnwnwwwwenwwwswnwnwewswnwnewwne
eewnewswnenwswwswwsweeseswnwwnw
wsenenenwnenenwnwnenenenwnenenenenenenw
swseswwswwswnwswswseneseeesw
eeenwnweeeseeeeeeeeeswee
seseneewsesesenwseseeseswsesesesese
swswwswsweswswwswswsw
seseseseseweeeeeeseeseswneeenw
nenwnenwneseneswnenwnenwsene
neneneneneneneswenenenenene
nwnwnwswnwnwenwneneneneeswnwnwnwwnwne
wswnwneneenenwneswnwneswnenenwswsenwnwe
nwnwnwswnwnwnwsenwnwnewnwsenwnwnwenwswnw
seneneneneenenweenenenenenenenenenew
nwwswnwnwnwwnwnwnwnwnwwsenwnwsenwenw
seseseseswsenesesesesesesesesese
enwwwwenwswwswnewwswwsesww
wnwsenwnewenewswswswseewwwwswswswe
seswswnwswwwswswenwneesenwswswswnwesw
sesenwnwswsesesesesenewsesesenwsesesee
wseswnwswseseseeneeswsesesesesewsesene
swwseneswnwwwswnwwewwnewweewsww
neswseenwseneneenesenenenewnenewswnee
eeseeseweeeseeeeseesesesee
esesewseseseseneseswsenweseeeesese
wwnwnwwwwwwwnwnwnwsenewnwse
seenweseseseseeeseswnweeseseeenee
swswwswwwwwwwwwwnewwwwnenew
nenenenenenenwnesenenenewnenenenenenwne
enesweeeeenweeneeenwsww
eeneeeeeeneeeseeeeeeewswe
sweeeeeeeeeeeneeneee
wnwnwwwsenenwwwnwnwwnwnesesenwnewsw
neneeenweeseneeswneeweesenwneee
seneeeseseswnesewswnwneswswnwsewwnwnwsw
nwneeenwnenenenwnwnenenenwnwnewnewne
neswnwsweesewswswnwwneswswwswneswwsene
seeseseeeenwswseeenesesesenwsesewse
nwnwnwnwnenwnwnenwnwnwenwnenwenewwse
enwnwnwnwnwnwnwnwnwswnwnwswnwswnwenwnwnwne
nwwwneneswswneeewnwwnwswswseeseseee
nenwnwswnwnwsewneneenwnwwnw
senwweweswnwneeneseeeswnweseswse
wnwwnwnenwnenwsesenwnwwnwnwswnwswnwnwnenw
wwnwnwsewnwnwwnwesweswnewwwswne
nenenewneswneneswneeweswneenwnesenw
eswnwwwsweseswwswswwwnwswswnwswsenw
eeeswsenwseeweeeeeeseeeeee
nwwwnwsewwnwwnwwwwnewwsewwnwwne
seseseesesesesesesenwseseseseseseseswsw
nwnwnwswsenwnenenenenwnwnwnwnwnwwnwne
nwsesewesenwnwnwnwswsewenwswnwnenwwe
newneseneneseswnwnwswnwewswnwnwseesw
eeeeeeneweeeneeneswneeseene
nwnwwnwnwnwnwwwswnwnwnwnwwewnwwswe
swswswseswneseseseswswseseswswswnwsesesesw
eeseneneseweneneeeneeneenwneewne
eseeswseeeeseeneseeeenwseeeese
sesesenwsesesesewsesenesesesesesesesesesese
senwseseseseseseseseseseseseseseswsesenwsw
neeneneswnenenenenenenenweneneneneswne
swswswseswwswswswswnwswswswswwseswswnwsw
neeeeeeseneeneswwneeeeeneeee
enweesweneneswweneeewenewenee
sewwswswwseneswwwsenwwswwwnewwww
wewwwenwseswnwwwwwwewnwnwnw
nwwenwsewswwwsw
neneneeneneneseneneweseenenweenenene
nwswswneswswwnwesenwsweswswswsw
swenwnwnwnwnwnwnenwsenwnwwnenwnenw
swseseneseseseseneswwsewneseewswnwsene
wneeneneswnwneneewneneneeneenenee
eenwneeweeeeeeesweeeee
seneeswnenweweweeweneeswseee
swseseesewswswsenwswswswswswswsw
wswwswwwswwswwwwnewwwwsewnesw
nwnenwsewnenenenwnenwnwnwne
neenwneneneneneseneneneenewnenenwnenesw
enwnwwnwnwesenwswnenwnwnwenwnwnwswnw
swnenwswsweseeswswswseseswwnwswswseseswsw
nwswnesweswswsewswseswnwswswswswneseswesw
swneseneswswwsenwswswswsw
eeeeseeeeeeeweeeeeneee
wnwwnwswewwnwwwwwwwseww
neenenwswnenweneeeeseneseee
neneweneeeneneneswnenweweeseene
neeswnesenenwnwnenenwswnenenwswwnesenw
senenwnenenenenenwnene
sewnwneseeweswseeseenesesenweswwwne
swswnewseswswswswswwseseswswseneswswswsesw
nwnwswenwnwnwnwnwnwnwnwnwnwsewnwnwnwnenw
eseneswswnwswnweneeeeeeeeeeee
nenwnenwnwnenwnenwnwnwneswnwnenwe
senenenwsweswsweseenwnwwswnwswswswnwwe
nweneeneseneswwneswneneenewneeneene
seeseswnesenwnwenwnwnweneswwwnenwnwwnw
eseseeseeeseesesenesenweeseswsesese
swswsesenwswswswsenwswneswswseneneswsew
nenwnwnwseewnwwnwnwsewnew
swswseswswswneweswswswwswswswswswswswswse
wswsweswswswwsweswswwnwswswswswww
swnewwsenwwswwnewnwwsewwswnwnwne
wnwwwwnwwwsewnenwneenwswsewwnwww
nenweeeeeneeeesweee
sesesenwswswneswenwswwswwneswnesw
swswsewswwswswswenewswsww
seswseesesesesenesese
nweeseseneswwewseswseneseeeeeese
swnwswswseswwsweswwwswwwwewwnw
wnwnwnwnwneswnwnwnwnwwnwnwnenwnwsenwnwnwnw
nesenenwwneneswnenwnwsewneenwnwnwnwnw
eweeneneeseneeenweneeeneseenene
nwwnwnenwsewnesewwewwnewwnwese
eseeseseeeeseseenweseeseseeesw
wwnwwnwwewnwnwnwnwwnwwwnwsww
wnenweewsesewww
nwseseseseseseweeseeseseseseseesese
seseswwseswswsesweswseseswswswsesw
wswswsweswswwswswswwswswwsw
eeeneenweneeeeeeeewseseene
neneneenwseseswswenewsenenenwwsw
nwnwsenwnwsenwnwwnwnwnwnwnwnwnwnwnwnwnw
eeneseseneenenwewneeeeeneene
wwswswswwwwswswswwswwnwsewsw
senewseseewnwswseseseswseseswseswsesese
seswseswnwnwweseneseswsesesweseswsew
nenwnwseswseeweewnwnwneswnwswwnwsww
nwnwnenwnwnwnenenenenwnwnenesenwsenenenwnw
sewnwneswsewwswnwwseewnenenweswne
nwseswnwswsesenwnwnwwswnenewseswsewe
newnweseswsesenwwnwwnwnwnwnwnee
swwnweswwneeswnwswenwnwswswwswwse
sewwnwswenwwwwsewnwwseswneeswneswe
wwwwwwwnwwnesewwwwwnwnwww
seenwwswenwswnweeeeeeseeewsese
wswnwwwwwsewnewwswsewswwseenw
nenenenwwenwnwnenenenwnwnenesenwnwwse
nwnwnwnwnwnwwnwenwnwnwnwnwnwsenwnwnwnwnw
seseswseswnwseseseseseseseseswnwsesesesw
wnwwwwsenenwsenwwnenwwnwwwwenwnw
nwnewseseswsewnwnenwswnwseenesewnwnenw
neswsewwwwweneswwwweswwwnenw
nweswneneeneeeeneneneneswneneeneee
wswneneseeswswsewsenweseseswenwnwsw
sewswnwnwnwnenwnwnwnwswsewwwnwnenwwne
swswwswswswwswnenwswswsweswsenwweseswse
neseswwwnwnwnewnwseswnwwwenwnwnwe
swwswswswseswneswswwswswswwswnwswsesw
wnwnenwneswwnwwnwnwwsenwwnwwwwnw
wwnewsenwwnwwnwwwnwnwenwwnwww
swseswnweewwswnewswwenesenewswnw
eneeseenwsesweeneenweenwwesese
sesesewswwswswswswseeseseseseseswewe
nenwenwnwwnwnesenenwnwnenwswnwnenenwe
seenweeeseseseesenwseswseswsew
nenwnenesenwwnwnenenwnwnenwnwnenenenwnw
nwswseewswnwneswswneseseswsewseswnwse
nweneswwnwnwwwewsenwwwwwnesww
neeswswswwwwnwsewneswswswsewwwwww
wswseswneswesewneneesesenwseenwenw
wewwswewwnwwsewwwwwnwnwwwne
ewseneesesesesenwseesesweseseseee
nwenesweeeeeneneeneneneeneeee
nwswseswsesesewswseseswseseneseswse
wnwnewneneneswewneneneeneneenenenene
nwnwnwnwnwnwnwnwnwnwnwnwwnwenw
wwswswwnwwwwswswwweswwwwsww
seseseseewseseswnwneeeseseesenesese
neenwnwnesenwswnenweenwsewnwwswwnwse
swswseswnwswseswswswseseswseswnwsesweswswsw
eseeeseenenwenesweneweeenwwse
nwwwwwwwnewwwnwsewwwewwwsw
swswseswseeswswseswswswswsenenwwseswsw
nwneswseneneseeseseeswseswsenwseseswsese
nenwwwwwwwwseseweswwwwwww
wsesenwwseeseneseneneswwseseeseswsese
swswswneswswswwwwwwswswswswnwsewswse
eesewsesewneswseneeseenweeswese
swsenwsenwswneswswswseswseneseseswsesenwse
wwwswnwsweswwesewwwwwwswwwe
eswswnwwwwnwweenwwwwwwnwwnww
seweeeneeneeeeenwsweneneewswsee
nwswnwnwnwwnwnwnwsenwnwnenwnwnwnwwnwnw
sweswwseseswsesesw
nwwnwenwswwnwnewwswsewnwwwewwwne
nwnwnwnwwwnwnwnewnwnwnwnwnwwsenwnww
wswswswneswseswswnwweewswwswswwswsw
neneneeneswnenwnenenesenewneeneeene
neswseseseneseeewewneseseseseseswnw
sesweswnenenwneneeneneneneenenwnwsenene
nwwenenenwseewwseseswnwwwwwenewe
nwnenwnwnenenenenesewswnenwneenw
neeneneneneenewseneneneenene
wwwswwesenwswneswswswwwswneswswswsw
sewwwwwwwwwwwne
seseeeeeseseseseweneseseswsesewsenw
seeseeeseewseeneseseeesesesesee
wswwswwwwswweswsw
nwswnwnenwnwneswnenwnwnwnenwnwnwnenwnwne
wswnenwnwnenwnenwswnenwsenenenenenwnwenwne
enweeeeeeeeseeeswewweeee
seeeesweseeeeseweseneenesenwsese
nenwnwswnwnwwswwsewnwnwnwnewnwwwnw
sesesweneweseswseseseswnwsesesesesesese
senewwwswswwnewwnewsewnwwenwsenww
wwwsenwnwwnwnwnwnwwnwwnwwnwsewnw
swswswswswseswswswswnewnwwnwswwwswe
seeeneeseesenweseeeewseeseswnwsw
wwswnewewsewnwweswwwwswswww
nwnwwnwnenwnwswnwenwnwnwnwnenwnwnwnwnwnw
neneeneneeneeenweewneneswne
nesenewenenenenwnwnenenesenewsenesewe
seneeseeswesesesesenweeewese
sesesesesesesesenwesesesesw
wnwwnwwsewwwsenenw
neneeneeeneneeeeenwesweeeee
eeeseneneneeneeneneeneewewee
seseseseseseswsesenwsesesesesesese
wsweswswnewswwsweswwswwswswwnwswne
wswseswwwnwswswesewswneswnwwwnee
eseseseswneseseeseseseswseneswnwsewsesww
nwnwsenwnenwnwnenenwswwnwswwnwneeee
neneeeneneewwneeneneneeswseneneeee
nenwewnwwwnwnwsenwse
nwnwnwnwnwnwnwnwswwnesenwnenw
nwweseseseseseeeseseseeeenesesese
nenwnenwnwnewswnenenenwnesenenenenenesenw
seneseseseseseseeseseseseswew
neseeneenenenenenenenenewneenenwene
nwnwnwnenenenwnwnenesenenenenwnenewnwne
swseswswseswnewswwswswseneswneswenwsw
eeneeseenwesweeneweeseenwene
wswseseseseneseseseseswwseneswesesenenw
sesesesesesewseseseseseseseeseneswsesew
nweswnwnwesesweseswswnwnweseenwsene
seneseeseeeeseweseeeseseesesese
wneeneeneweneseneneneesenenenenene
seseesesesewwseseseseeesesenwsesese
neneweeseneewnwseneneeswneneeeneene
neswenwswseseswswneswnwenenwseswsenwnw
swswnwseseseseswswsweswnwsenwswnwsesesese
wnesenwwwweswwwwwwwswwwww
eswnwwswweweeeswnweswnenweseww
wwnwwweseswnwwnweseeneswswe
wnwnewwnewwwwwwnwsewwwwwsww
neswnenenwneneneneneesenewneneeeenene
wneewnewsenwsenwnewswesenwswwnewsw
nwsesesewwnenwnwe
nwnenwnwnwwnewenwsenenwneesenwnwnewse
seneseswseseseswseswsewnese
swseswswswseeswswswswnwsesesesw
newnwseeenwnwwswnenenwnwnenwnw
swwwnwswswswsewwswewwswwswwwnesw
nwnenwnwnwseseneenwnwnenenwnwnwnwsewsw
seeseseseseseseeswnwsesesesesesesenw
sewenewnwneneewnwnwnwnwnenenwnwnenwnw
neneneesenenwnwwneneneneneneenenwneswnw
wwwwswswswswewwenwnwwswwwswsew
senwwwwwwwnwwwwwwwwwweww
sesesesesesesesesenwsesesese
nwwnwnwnwnwnwnwnwwnwnwwnwsenwnwnww
nenwnwnwnwsenwnwnesewnenwnenenwnwnwnwnenw
nwneneeeeeeeeeeneeeeseswee
swseswseswswswswswswswseswnwsweswswswsw
swswswnwswswswswswseswswswswneswswswswse
seseewsesewwnwnesenenenenenenewnenesew
neswseswnwseswswswesesweneswnwseswnwsew
senesewnwswwseseseseseeeneeseeese
nwsweenwenwnwnwwnwnwwnwnwnwnwwnwswsw
seseswswswnenwseswneeswswswsweseseswnw
seseswseswswseseneseewseswswseswswsewse
swswswwsesewswswswswwswnwwwwneswswnesw
eeeeeeenweseeesw
eeeneeeneeweseeeee
nwnenewneneneenwsw
neeneswenwweeswewwseenenw
nwswnwewwnwnwnwwsenwnwnwnwwnwnwnwsenww
enewenwseneneswnwnesewsewnenenwneseswne
seneswswseseswswesenwsesw
nwnwnwwwnwnwwnwnewnwsenwwnwnwnwewnw
nwnwnwswswwnwsenwnenwenwnwsenwnwnenwnw
nwseneswnenwwnwnenenenwnenwnenene
wswswswswwwwswwswsenwwswswswsw
wwwnwnwwenwwsenwwwwewwwnwww
eseeneswseenwwseeeeswsesenwswwe
neseeswnenwwnewsesesewsweneseeswsese
seswswwseswswswsenwseseseseseeseswseswnw
swnwswwnweweewwwswwwwswesww
nenwsenwenwnwnwnwnwnwnwnwwnwnwnwnwnwnw
swswseswneswswswsenwseswswswnwneseewswsw
neneweenenenesenenene
swneswswswswswswswswswsw
nenenenenenenwnenenesewnenwnwnenenesenene
eneeseeeeeeeeeeseeewesee
seeseeseseeneseseeeseseseswese
seseswenwswnwseswswswswseseeswswseseseswse
nwwnwwnwnwwnwnwnwseewnwnwnwnwnw
seneswswswwswswseneswswseswswswseseswsese
nenenwneneneenwnwwnenwnwseneswnenenwnw
seseewsenwneeneswenwnwneswenenenese
nwnwsenenenwnwnwnwswnwnenwnwnenenwnenwne
nwnwnwwenwswnwnwnwnenwnwnwwnwwnwwwsww
swswnwseseseneswneneesewseenwnwsesew
neneenwnewneswnenwnenenenwne
wswswneseseswseswsesewswswseseseseseese
nwnwnwnenwnwnwwnwsewswnww
wwewnwwwnwwwwnwwwnwnwnwwwsw
swsesewsewnenesenesesesesesenweswsese
newnenwswnwneneweswsenenwenenwnenwese
swswswswswwswwswswswsewswswnwswswswwe
ewswneswnwwswwwwwsewwwwwswwww
wwwwwwswwnwnwwwwweewwwww
wswseneswnwneswnwnenenenwwsenwnenwnese
nwnwswneswnwnenwwnenwnwenwnwnwnwwnwese
neenenenenewneneneneneenene
weewneswseneneseneswnenww
sesesesesesweseseeeseesewseewwenw
nwnwnwnwnenwnwnwwwnwsenwnwwnweswnwnw
nwnwnenwwwsenwnwnwnwnwnwnenwnenwnwnwnesene
swseseseseswseseseseseswsesenwnwsesesesese
wwwnwwnwnwnwewwnwwwewswnwww
seswseenwseseeeweee
swswswnenwseswnwseeseswneseseseneesesww
neeneenwswesweneneswswneeneeswene
nwswswweesewwwnenwwewwwneww
neeeeeewseseseeeseseee
sesenesesesweseseeswseswseswwseswnewnww
newenwsewseweseseseseseswseseenesesee
seseeseewenwwseeseseseewneesesewse
nenenenesenwneeneswneneneswneeeneneee
sesesesewseseswseseseseneswseseseswsese
newnwnenenwnweneneeswnenwnwsenwnwnenene
swswswseswswseswswswneseswnwswseseswesw
nwneswswnwnwenwnwnwnwnwnwne
wnewswwsewwenwwwwnwwnwwwnew
swsenweseseeeenwseseeeseseneesewse
wwenwwnwnwwnwseewnwwewsewnw
nenenwnwneseswnenwnenwnenwnenenwnenenwnene
seneswswswswnwswswswswswswseswswswswswse
nwweswwwswseswwwwnewwwwwswwswsw
wwneswnwnwnwenwwsewwnwnenwnwwnwsenesw
sesewnwnwnwswsenewwnenwnwnenwnwnwnwnwnenw
swnwswswswwswswswswneswneseswswswswswsw
wswwneswswnewswswsesesesesesenweswsw
neseseswseseneswwswsesewseseseseswswsese
swewneeswswswswsenw
esenwnenwswsewswswseswseswnwseswswswswse
swewswneeeseseseeeeeweeenenwe
nwwnenenwwneseneseneneewseneneneeswne
nenewnenwenwneweswnwne
eeeeeeeeeseseewweseesenesene
swnwswnwenwewwwswnwswnwwnenenesesw
seenesweswsesweeeenewneneenewesw
seeseeweseseseseseseseseseseseewsese
swswswneseneswswswwweswseswseswswswsw
sweeeeeeeeeneeneneeswene
eswwsenwswswswseswswswswswswwswnwneswsw
sesesesweseeseneeseseseseseseseseswene
enweseseeeseeseseseneeesweeese
wwswwwwwswwewwnenewwwswwww
seewnewenwneseeeweeesweeeseene
seneseneneneenenewneenenenenewnenene
wnweseswswnwnweswnwenwswseeswswswswnw
nwneneneeneneswneneneneneneneneneneswnenene
nwnwnenwnwnwsenwnwswnenwnwnwnwenwnwnese
nenenwneneneneneeneeneeneneneeneswne
nenwneeseenenewsesweneenenenwneeene
neneneeneeseewneeneewwe
wenwsesweseeeenwesewenweesesese
nwnwwnenwnwnwsenwsenwenenwnenwnwnwnwnwnw
swesesewseswswseswswswseneneseseswnwsesw
nwnenwnwnwnwswnwnwnwsenwnenwnwswnwwnwne
eswwswseswsewenwnewwnewseswneswwnwsw
swseswsesesenwseseseseswsese
esweswnwewsenwsewse
wsesewwwwwewnenewnwwswwwneww
swseseswwswswseseswswneseswswsesewswneswsw
swswswswseswseswswswswnwnwswswswseswnesw
nenenesenenenenenenenenenenenenwneneneswne
eseswesewnwseeseneesweewseseenwese
swwswswswnwseswswswswwswsweswswswswswsw
neseeenwnweswenwsewseseneswwswnwsww
swswwswneneswswswswnewswseswswsenw
senwnenenweneneeneswneeneneeseeswnew
nenwnwnenwnwnenwswsenwnenenenenwnwwnwe
nwwnwnwwnwnwwnwnwnwnwnwnwenwwnwnw
swswswseswswswswswnwwseswenwswseswsweswe
wnwwwenwsewswwwwswnewwwnwwww
nwwwnwnewsewwwwnwnwwwnwnw
nwswweswewswswnesw
sewsweseswswswswnwsweswswswswswswswse
ewneneseeseneeeeeneeneenwnwnee
seswswswwseswswseswswswswswneswsese
eeeneeseeeeeseseswesese
neswsenwwenwnwsenwswnenenenenw
eswewswwneenenenenwsenwsewnwenewnw
wwswwswwenwswwewswswwwwwwsw
eenenenwwnesweeenenewseswenesene
seswneneneseswwenwnweneneneenenenene
wenwwnwswwwnwwwnwnenwnwwnwswwe
nenenenenesenwneweneenenenenenenesene
wwwwwwwwswwswwwnwwswswesww
wwsesenwnwnwnwwnwnwnwnwnwnwnwnwsewnw
senewnwenenenenenewneneneneneneneswneene
sesewnwneneneneneneneneewneeneswnw
swwswswswswswswnesw
swweneswnwwnwwneswseswswesewwswse
neneesenewnewneneenenewnenenenenene
nwnwswneswseswnweee
wenewwwseseswnewwwwnwwswswswwnw
swsewnenwenwsenenwse
nenenenenwneneneenenwnesenenenenenesenene
newwwwnwsewwwwwswswwnesewsww
wnwenwwnwwswnwwnwwwwswnwnwenwnw
weswswwwewsweswswwswwwwswww
seneeeseenwsesenwswsweesenwseeeewe
swnwenenenenenenwsenenwnwnenesenenenwnwne
nwnwnweswenwnwnwnwnwnwwnwswwne
swswwswswswseswswswswsweswnwswswswesw
nwnenwnwnwnwneswnwnenenenenenewsenenwnenw
nwsesenenenenenenenenenenenenenenenenwsenew
eseeeeeeeeeeeeweene
senwnwnwwenweswnenwnwneewnwnwwww
swnwsenwswneneneenweswseweneneneee
weeeewseseeeeseeeseseseseee
wnwenwnwenwwneswnwwnwneneeswnwenw
nwsenwnwnwwwnewwnwseneseswnwnwwnenwnw
nwnenenwsenwnenenenwnenenenewnwnwneew
senwnenwnenwnwnwnwnenwnenenwwsenenwnwnw
enwwwnwnenenewneneswenenesewenene
nenweneneseeenenwenwnenewneswseneswe
wneseneneneenwneneneneneswnenenenenenenene
neneneeseeneeneweneeneneenene
eenesweeneneneneneneneneeenene
esweseeneeeeneeneneeeeewnwse
sesesweswseseseswseswnwseswseseseswsese
nwnenwnwwsenwnwnwnwnw
nwenenweneneswsesweeneneewneeene
ewneseseeswseeneeeseew
swswwswswnwswswswswwswseswswswnewswewsw
sesenweseeseeeneneeseweswsesesesw
nwsenwseeswswsewwsenenwwnwenenwswwene
swswnwwseeneswwnwnew
swswswseswseswswnwseswswswseeenwswswsese
swnwneswnwwsweswseswwwnwswwswswewse
nwnwnwnenwewnwnwnwnwnwneneswnwnwnw
seseseswsesesweswseswswseneswwseswswsese
swwweswwneswswwswwwseesenwnewse
wswwnwwsewnewswwwneswnewweswswswne
eseenewneneswsesenwneneeneneswswnenewsw
seswesenwnwnwneswswnewwnenwneseneenew
wsweswswswswswswneswswwwswneswswwswwse
swneneneenewneneneenwwsewneeeneswne
nwneswnenwwswnenwsenwnwnwneenwseenenenwsw
seseswseswseseseneswswsweswswswsewsesw
ewneneseeneeneneswnw
eeseswnwseseeeeeseseswnweseeseee
wwewseswwwswswwwnenewswswwwswsw
nwewwenwswnenwseswwnwwwnewnwnwswe
seswseswsesesweswseswsesenwsesesesesese
swswswwwswwswewswswnewwewswwwsw
swnesesenwewwseseeswnewnenwwenese
swnwwseswenwsenwneseseseseseseenwsesw
nesenewsenwnweswwwwnwneswnwwsenenwne
ewnwnwnwnesenwnenwnwwswnwsenenwenwnw
esesewneseseswsenesenwwseswsesesenenw
seneswwwnwenwseswnwwwwwswswwene
eswwnewnenenwnwnwnenwnwnenwsenwneene
wneseseesenwnwseneneneswswwwwnwswenese
nesenwnwwnesenesenenwneswnwneswnwnwnenene
senesesesewseseseseseseseseseseesesese
neweeeeneenenwswenesweeeswneee
swneneenenenewnenenenwwnenwsweenenene
nwwenwwwseswswwneswwsenewenwnwnw
nenenenenwsewneseneswneswnenenwne
swswswwswsweswswswswswswsw
nenenwsenwnwnenwnwnenenenwnenenenwneswnw
neneswnwnwnwnwnenwnenwenwnwnwnesenwnenw
nwnwswswswewswswswswswswswseswswswswsw
weeeeeeenee
swnwswswsenwseneswseeseswswneseseswswnwse
swswwseseswswneswseswswneswseseneswswsw
weesweneseweeenesewesweneesee
seswswswseseseseseseseneseswsesenwesese
eweneseeeseneewnwneeeneneenese
swwnenwswwnwnwnwnwswwswenweenwnww
nwwwwwswwswwwwwswswswwswswwe
eneenwneseseeneneeenwseneswneenew
sesesewneswnwnenewneseeneswnwnenweew
eswswswsenwnwnwnewswnenwseswnenwnenee
enwwwesweeeeeeeeseeseeeeee
eseeeeeeeseeeneseswwseeeeee
nwnenenenenenwnenenenenwneswsenwse
weseseseeseseseseseseseeeenesewse
neeneeeweeesweeswenweeswnwenw
nwwwneswswwswswewewwseswswswww
nenewnenenwnwnwnwnwnenwnwnenenesenwnwnw
esesesenesewseseneseseswsese
sesweswneneneneswwnewnwnenweenenenwsw
nwneneswnwswswwnewneneneseseenwsewnese
wneseewnwnwenwnesenwwseseswwnewnwe
senwwsweeesenwse
wnewwnewsewwnwseswwwswnewwwsw
nwnwwnwnenwnwnwnenwnwwnwsenenwsenwsenw
enwwwwnwwnwnwwwnww
wwnwnwswewneenw
wnewewswwwwnwswwswswseswswwnesw
wneenweweneeweseeeeseeeseee
eeswswweeeneseeeneenwswseseenw
nenenenwnwnwnwnwnwswnwnewnwnenwnwnwenwne
nwswswsenwseswnesewnwswswswswseswneswsw
seeweeeeeseseseseeneseseseseswse
sesewneseswneseeseswseesewwswsesesw
nweneswsesenewweseswwneseneeseswswe
senwseseswsesesesenwesenwsesesewesesesw
eneneneeenwnwnwnwseseweneswse
neswneswnenenewswnesenwnenenenenwnwnesw
neswswseswswseswswseweswswseswswswswsesww
neeeeeweneesw
eneneeeeneswnene
swswswswneswswswswsewswswswnwseswneswswsw
wnwesweneneseseneweeesewswwwnwe
wnwewwwnwnwwnwwenwsewswnwswww
neeswnenwnenwsenwnenewweswsenenwnwswnw
nwswnwnwwnwnwnenwnwenw
swneswswswswwswswswswswswswwswswsw
swnwwnenwneswneenenenenenenwseeeesesw
wnwnwnwnwnwnwnwnenwnwnwnwnwswwswnwnenwnw
seswswnenwseswnwsesweseseseseswseneesww
seewnwnwswneweswwwenewwewsenwse
swswseswswswswnwswweswseswseneseswswsw
neneneeeneeseeswsweeeewneeeenw
swseswseswswswneneseswneswnwne
neeeneeneneneneneswnwenene
swsewewnwnwnenewnewnwwseewseesese
nwnwnwewnenwenwewnwnwnwnwnwswnwnwnwnw
nwwweeeeseswseseseseesenweseewe
sesesewswsweseseswseswswseseswswneenwnw
nenenenenenenwneneneseswneneneswne"""

# input_ = """sesenwnenenewseeswwswswwnenewsewsw
# neeenesenwnwwswnenewnwwsewnenwseswesw
# seswneswswsenwwnwse
# nwnwneseeswswnenewneswwnewseswneseene
# swweswneswnenwsewnwneneseenw
# eesenwseswswnenwswnwnwsewwnwsene
# sewnenenenesenwsewnenwwwse
# wenwwweseeeweswwwnwwe
# wsweesenenewnwwnwsenewsenwwsesesenwne
# neeswseenwwswnwswswnw
# nenwswwsewswnenenewsenwsenwnesesenew
# enewnwewneswsewnwswenweswnenwsenwsw
# sweneswneswneneenwnewenewwneswswnese
# swwesenesewenwneswnwwneseswwne
# enesenwswwswneneswsenwnewswseenwsese
# wnwnesenesenenwwnenwsewesewsesesew
# nenewswnwewswnenesenwnesewesw
# eneswnwswnwsenenwnwnwwseeswneewsenese
# neswnwewnwnwseenwseesewsenwsweewe
# wseweeenwnesenwwwswnew"""

import re
from time import time

r = re.compile(r'ne|nw|se|sw|w|e', flags=re.I|re.X)
tiles = [sorted(r.findall(x)) for x in input_.splitlines()]

# n+, s-, w-, e+
positions = []
for tiles in tiles:
    counter = [0,0]
    for move in tiles:
        if move == "nw":
            counter[1] += 1.
            counter[0] -= 0.5
        elif move == "sw":
            counter[1] -= 1.
            counter[0] -= 0.5
        elif move == "ne":
            counter[1] += 1.
            counter[0] += 0.5
        elif move == "se":
            counter[1] -= 1.
            counter[0] += 0.5
        elif move == "w":
            counter[0] -= 1.
        elif move == "e":
            counter[0] += 1.
    positions.append(counter)

solution = 0
tiles = []
for i,c in enumerate(positions):
    if not c in positions[:i] + positions[i+1:]:
        tiles.append((True, (c[0],c[1])))
        solution += 1

print("Part #1:", solution)

def getNeighbours(position):
    tx,ty = position
    return [(tx+1.,ty), (tx-1.,ty)] + [(tx+x,ty+y) for x in [0.5,-0.5] for y in [1.,-1.]]

def getBlackNeighbours(position, tiles):
    neighbours = getNeighbours(position)

    count = 0
    for n in neighbours:
        for black,position in tiles:
            if black and n == position:
                count += 1
    return count

t = time()
for k in range(1,101):
    print("ROUND", k, end=' ')

    # Adding neightbours as white
    for i in range(len(tiles)):
        black,position = tiles[i]
        if not black:
            continue
        for n in getNeighbours(position):
            if not (True, n) in tiles and not (False, n) in tiles:
                tiles.append((False, n))

    # Flip
    new_tiles = tiles.copy()
    for i,(black,position) in enumerate(tiles):
        count = getBlackNeighbours(position, tiles)

        # Flip to white
        if black and (count == 0 or count > 2):
            new_tiles[i] = (False,position)
        elif not black and count == 2:
            new_tiles[i] = (True,position)
    tiles = new_tiles

    count = 0
    new_tiles = []
    for black, position in tiles:
        if black:
            new_tiles.append((True, position))
        count += black
    tiles = new_tiles
    print(count)

solution = count
print
print("Part #2:", solution, '(', time()-t, ')')
